[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated

[database.identity_db]
url = "jdbc:postgresql://wso2-is-postgres-database:5432/WSO2_IDENTITY_DB"
type = "postgre"
driver = "org.postgresql.Driver"
username = "postgres"
password = "password"


[database.shared_db]
url = "jdbc:postgresql://wso2-is-postgres-database:5432/WSO2_SHARED_DB"
type = "postgre"
driver = "org.postgresql.Driver"
username = "postgres"
password = "password"


[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"
